version: '3'
services:
  db:
    image: postgres:11-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASWWORD: 'postgres'
  redis:
    image: redis:latest
    restart: on-failure
    ports:
      - '6379:6379'