# Generated by Django 2.1.7 on 2019-04-21 16:21

import api.models.pitt
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitt',
            name='audio',
            field=models.FileField(upload_to=api.models.pitt.user_directory_path),
        ),
        migrations.AlterField(
            model_name='pitt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitts', to='api.User'),
        ),
    ]
